server:
  port: 8080
  servlet:
    context-path: /payment-service

spring:
  application:
    name: payment-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms_payment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    
    # HikariCP连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

# MyBatis-Plus配置
mybatis-plus:
  # 配置Mapper XML文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.bytz.cms.payment.domain.entity
  
  # MyBatis-Plus全局配置
  global-config:
    # 数据库配置
    db-config:
      # 主键类型（INPUT为手动输入）
      id-type: INPUT
      # 逻辑删除配置
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 字段策略（NOT_NULL：非NULL判断，NOT_EMPTY：非空判断）
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
  
  # 配置
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 缓存
    cache-enabled: false
    # 懒加载
    lazy-loading-enabled: false

# 日志配置
logging:
  level:
    root: INFO
    com.bytz.cms.payment: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
